### ISSUE TITLE
Suggestion: Popover arrow color customization and removal

### ISSUE THREAD

**Issue by zespere** [mishka-group/mishka_chelekom#116]
After I added the borders the arrow makes my div look as if it had a gap in its border, having a way to choose the arrow's color could solve the problem.

Although some way to remove it also could be pretty nice.
![popover_arrow](https://github.com/user-attachments/assets/5bc4d781-e69a-41b8-9e82-854dab20451a)

**Comment by MonaAghili** [comment]
Hello @zespere
Sure, we will add this feature today.

**Comment by shahryarjb** [comment]
Hi Dear @zespere, we add an option for your suggestion. You can use it from master.

### Example usage of `show_arrow`

If you do not set this property, it will be set to true and the arrow will appear

```elixir
<.popover>
   <.popover_trigger></.popover_trigger>
   <.popover_content show_arrow={false}></.popover_content>
</.popover>

<.popover>
   <.popover_trigger></.popover_trigger>
   <.popover_content show_arrow={true}></.popover_content>
</.popover>
```

Thank you
