### ISSUE TITLE
Docs reflect master/main vs what is released.

### ISSUE THREAD

**Issue by ptinsley** [mishka-group/mishka_chelekom#157]
First off, I'm excited to see this project coming to life, keep up the great work! I've just started attempting to incorporate these components into a new project I'm working on and ran into an issue with the navbar component and a slot that was making Phoenix real angry.  I went and pulled up the source in Github and thought I was losing my mind but then realized that my local is tied to 0.0.1 vs master.

I swapped that out for `{:mishka_chelekom, git: "https://github.com/mishka-group/mishka_chelekom", only: :dev}` and everything started working just fine. A lot of projects have a pulldown for versions of docs (tailwind screenshot attached) maybe something like that could be done? Since this is such a new project and is changing quickly it would also probably be good to include master in that list for people who want the bleeding edge stuff.

Since that is probably a decent undertaking, you could suggest that people use git directly for now... That way the generator output would match what the docs say.

<img width="376" alt="Screenshot 2024-11-29 at 11 14 13 PM" src="https://github.com/user-attachments/assets/5cc2316e-4bc6-4135-bb68-fc095ff0ba1f">

**Comment by shahryarjb** [comment]
Hi dear Paul,

I hope you're doing well. We're truly grateful for the support of amazing community 🥹. 
You're absolutely right—unfortunately, our team is quite small, and with so many components and the extensive changes from version 0.0.1 to 0.0.2, we haven't had enough time to dedicate to the documentation yet.

But rest assured, we’ll definitely come up with a solid plan for it in the future. 
Thanks a lot for your suggestion; we really appreciate it!

---

Until the new version is released, as you mentioned, please use the **master** branch. You can refer to the latest `hash`, and if you have any questions, suggestions, or feedback, feel free to reach out to us here. We’ll make sure to get back to you as soon as possible! 🙏🏻🙌🏻

**Comment by ptinsley** [comment]
No worries at all, I know how much of a bear carving out focus on docs is. Just wanted to get something logged as it's hard to get the first-time user experience when you are so close to the software. I'm perfectly happy using master, especially since it's a generator and I'm choosing when to bring new stuff in...

**Comment by shahryarjb** [comment]
♥️♥️🙏🏻🙏🏻
