### ISSUE TITLE
Suggestion: copy to clipboard component

### ISSUE THREAD

**Issue by zespere** [mishka-group/mishka_chelekom#177]
I think it would be nice to have a "copy to clipboard" component.

example: https://fly.io/phoenix-files/copy-to-clipboard-with-phoenix-liveview/

**Comment by shahryarjb** [comment]
I hope you're doing well. Thank you for supporting our project with your suggestions to enhance its features. 
Copying to the clipboard currently requires JavaScript (we have task for it and button for dark/light mode), which our generator does not support yet.

All the sections on our demo website where you can copy code use this method. However, we are currently working on a JavaScript parser written in Rust, and we will definitely include it in future versions.

If you have any questions, suggestions, or criticisms, please feel free to either tag me here or create a new issue for it.

Thank you for your cooperation!

**Comment by shahryarjb** [comment]
I think we are close to have all components that use pure js

Based on: https://github.com/ash-project/igniter_js/pull/1
