### ISSUE TITLE
For loop for components

### ISSUE THREAD

**Issue by kantum** [mishka-group/mishka_chelekom#184]
I'm trying to use the tabs component like this:

```heex
<.tabs id="bob">
  <%= for category <- ["A", "B", "C"] do %>
    <:tab><%= category %></:tab>
    <:panel>
      content
    </:panel>
  <% end %>
</.tabs>
```

But I get this error:

```
invalid slot entry <:tab>. A slot entry must be a direct child of a component
```

Is there a way to do this right now or does it need to be implemented in the components?

**Comment by shahryarjb** [comment]
Hi @kantum , I hope you're doing well.

Look, you can't create a `for` like this. The **LiveView** structure doesn't allow it.

You need to proceed like this:

```elixir
defmodule MishkaWeb.Components.TabsLoop do
  use Phoenix.Component
  import MishkaWeb.Components.Tabs

  @doc type: :component
  def tab(assigns) do
    ~H"""
    <.tabs id="tabs-loop">
      <:tab :for={tab_item <- ["tab1", "tab2", "tabs3"]}>{tab_item}</:tab>

      <:panel :for={tab_c <- ["tab1_content", "tab2_content", "tabs3_content"]}>{tab_c}</:panel>
    </.tabs>
    """
  end
end
```

In the future, I’ll release an update where you can, for example, pass a list of maps to the component, and it will generate the content for you. However, this feature will be available in the next version, 0.0.3. For now, you should stick to the method shown above.

#### Example:
```elixir
[
  %{title: "tab1", content: some_content1},
  %{title: "tab2", content: some_content2},
  %{title: "tab3", content: some_content3}
]
```

If you have any other questions, please feel free to reopen the issue or tag me. You can always count on my help!
