### ISSUE TITLE
Darkmode enabled by default?

### ISSUE THREAD

**Issue by tanguilp** [mishka-group/mishka_chelekom#204]
With a fresh install, dark mode is enabled by default. That is the widgets show in dark mode. Not sure how to disable it :thinking:

**Comment by shahryarjb** [comment]
Hi @tanguilp , if you add dark mode class to your html tag, yes it is enable
```html
<html lang="en" class="[scrollbar-gutter:stable] dark"><head>
```

**Comment by shahryarjb** [comment]
@tanguilp I close this issue if you have any problem. please tag me or for new issue create new one
