### ISSUE TITLE
Docs: Example modal freezes docs page

### ISSUE THREAD

**Issue by dmitry-sidorov** [mishka-group/mishka_chelekom#74]
https://mishka.tools/chelekom/docs/modal

**Subject**
The last example:  "On cancel prop" modal

**Reproduction**
Press `"On cancel prop"` button from the last example. Press `"cancel"` button on appeared modal. Page is freezed now, it's not scrollable anymore. If modal is opened one more time and canceled with `"X"` button or `"Esc"` key, page is alive again.

**OS**
MacOS Sonoma 14.5 (23F79)

**Browsers**
1. Google Chrome version 129.0.6668.90, (arm64)
2. Safari version 17.5 (19618.2.12.11.6)
3. Firefox 131.0.3 (aarch64)

**Comment by shahryarjb** [comment]
@dmitry-sidorov Thank you for report 🙏🏻🙏🏻♥️. it fixed
