### ISSUE TITLE
Docs: Modal prop "title" is required

### ISSUE THREAD

**Issue by dmitry-sidorov** [mishka-group/mishka_chelekom#75]
**Subject**
[Modal](https://mishka.tools/chelekom/docs/modal) prop `"title"` is marked as not required in documentation, but modal component requires it and raises an error on compilation.

**Documentation**
![Снимок экрана 2024-10-29 в 23 02 20](https://github.com/user-attachments/assets/e7b86510-9848-42e8-a5d5-3fc7f8250cd7)

**Error**
<img width="681" alt="Снимок экрана 2024-10-29 в 23 06 11" src="https://github.com/user-attachments/assets/d7c7f9a1-c62b-4cf1-8bdc-ade7f8f6624d">

**Expected result**
Required: Yes

**Comment by shahryarjb** [comment]
@dmitry-sidorov Thank you again, for temporary fix you can change the modal component, just add `default: nil`.

```
attr :title, :string, doc: "Specifies the title of the element"
```

To this:

```
attr :title, :string, default: nil, doc: "Specifies the title of the element"
```

After this if it does not work please tell me.

I will fix this

**Comment by dmitry-sidorov** [comment]
Thank you for work around :) I use modals with title for now 😆

**Comment by shahryarjb** [comment]
Thank you for helping us, you can update your `dep` from master and i fixed it.

Sorry for these bugs, we will start E2E test after some release.
