### ISSUE TITLE
Variant inconsistency: separated vs seperated

### ISSUE THREAD

**Issue by ChristianAlexander** [mishka-group/mishka_chelekom#80]
Hi there!

While testing out variants, I noticed an inconsistency that's found on the documentation site and within the accordion component itself: `separated` and its common misspelling `seperated` are used interchangeably in the variant options.

![Screenshot 2024-11-01 at 07 05 29](https://github.com/user-attachments/assets/f5297f60-921b-48f9-b3b2-6f99926a2a85)

As a result, the generator only supports the misspelled `seperated`.
https://github.com/mishka-group/mishka_chelekom/blob/c8d10602813786e83ced095980da17e8de3e2d14/priv/templates/components/accordion.eex#L34

It looks like the List component may also have this issue.

**Comment by MonaAghili** [comment]
Hi @ChristianAlexander ,

Thank you so much for identifying the issue in the document and reporting it to us. We appreciate your attention to our project, and we’ll resolve these typos in the project soon. I’ve already addressed this specific issue and will submit a pull request shortly.

Thanks again, and please don’t hesitate to report any issues you come across in the future.
