### ISSUE TITLE
Suggestion: Make it possible for toast to disappear after a couple of seconds

### ISSUE THREAD

**Issue by zespere** [mishka-group/mishka_chelekom#86]
Suggestion: Make it possible for toast to disappear after a couple of seconds

**Comment by shahryarjb** [comment]
Hello dear friend, I hope you're doing well. You can now accomplish this with your [LiveView JS module](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.JS.html) using. You can make a div visible after a certain period or mount it after a set time. The focus of this version has been on building foundational components and infrastructure. Starting from version 0.0.3 or 0.0.4, we’ll move toward live components that maintain their own state, and we’ll definitely implement this feature there.

Please feel free to provide any examples or further details here if you have specific cases or other relevant points in mind.
