### ISSUE TITLE
Toggling Overlay (Drawer, Modal, etc.) components 

### ISSUE THREAD

**Issue by kwayebopp** [mishka-group/mishka_chelekom#95]
My use-case is having *a single button control both showing and hiding* (i.e. toggling) a `Drawer` component. Is there a way that this can be accomplished? I've been trying to work this out unsuccessfully. 

Suppose I have a button that shows a `Drawer` when clicked:

```
  <button phx-click={Components.Drawer.show_drawer(%JS{}, "drawer", "left")}>Drawer Button</button>
  <.drawer
    id="drawer"
    variant="shadow"
    position="left"
  />
```

It clearly works at showing the `Drawer` on click. However, when the button is clicked again, the `Drawer` remains open. This is true even though the `Drawer` internally implements a `phx-click-away` attribute: although the `hide_drawer` function is called, since clicking the button fires the `show_drawer` function, the hiding is immediately negated.

I've tried implementing a custom `toggle_drawer` function, but it takes two clicks to open the `Drawer`: 

```elixir
  def toggle_drawer(js \\ %JS{}, id, position) do
    js
    |> JS.toggle(
      to: "##{id}",
      in: "transform-none",
      out: translate_position(position),
      display: "block",
      time: 300
    )
  end
```

I understand that this toggling behavior could probably be done by wrapping the `Drawer` in a stateful LiveComponent and managing the `@show` attribute, but that seems rather inelegant and arguably adds unnecessary complexity.  The `toggle_drawer` function I've implemented gets pretty close, if it were not for the "dead" first click.

**Comment by shahryarjb** [comment]
Hi dear @kwayebopp ,
In regard to the Overlay for the Drawer, my colleague will be responding to you soon. However, for the other issues you mentioned, we will definitely include an example in the upcoming release and test it thoroughly. Please note that the show function is server-side only, and for LiveComponents, we are not planning to go in that direction in the current versions. The Drawer is designed as a stateless component using a JS module.

Please allow me some time to test it, and I will get back to you soon.
Thank you in advance

**Comment by MonaAghili** [comment]
Hello dear @kwayebopp 
Thank you so much for considering our library and for taking the time to test it. We truly appreciate your help in identifying any issues.
Currently, I’m working on updating the color schemes for components. Once I reach the components you've mentioned, I will make sure to resolve the issue you’ve reported.

Thanks again for your patience and support.

**Comment by shahryarjb** [comment]
@kwayebopp Hi again, I saw some examples about this problem the Overlay (on whole page) can help use not to create custom button and so much JS module and Live Component payload. we will add it in this version.

Thank you for this suggestion and bug report
